services:
   rabbitmq:
      image: "rabbitmq:3-management"
      container_name: rabbitmq
      ports:
         - "5672:5672"
         - "15672:15672"
      healthcheck:
         test: ["CMD", "rabbitmqctl", "status"]
         interval: 10s
         timeout: 5s
         retries: 5
      networks:
         - mynetwork

   mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
         MYSQL_DATABASE: keycloakdb
         MYSQL_USER: keycloakuser
         MYSQL_PASSWORD: keycloakpass
         MYSQL_ROOT_PASSWORD: rootpass
      volumes:
         - mysql_data:/var/lib/mysql
      ports:
         - "3306:3306"
      networks:
         - mynetwork

   keycloak:
      image: quay.io/keycloak/keycloak:24.0.3
      container_name: keycloak
      command: start-dev --import-realm
      depends_on:
         mysql:
            condition: service_started
      volumes:
         - ./keycloak-realm:/opt/keycloak/data/import
      environment:
         KC_DB: mysql
         KC_DB_URL: jdbc:mysql://mysql:3306/keycloakdb
         KC_DB_USERNAME: keycloakuser
         KC_DB_PASSWORD: keycloakpass
         KEYCLOAK_ADMIN: sezenhuddam@gmail.com
         KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
         - "8080:8080"
      networks:
         - mynetwork

   notification:
      build:
         context: .
         dockerfile: notification/Dockerfile
      container_name: notificationservice
      depends_on:
         rabbitmq:
            condition: service_healthy
      environment:
         - RABBITMQ_HOST=rabbitmq
      ports:
         - "8002:8000"
      networks:
         - mynetwork
   user:
      build:
         context: .
         dockerfile: user/Dockerfile
      container_name: userservice
      depends_on:
         mysql:
            condition: service_started
         rabbitmq:
            condition: service_healthy
         keycloak:
            condition: service_started
      environment:
         - RABBITMQ_HOST=rabbitmq
         - KEYCLOAK_URL=http://keycloak:8080
         - KEYCLOAK_REALM=ptmanagement
         - KEYCLOAK_CLIENT_ID=ptmanagement_clientId
         - KEYCLOAK_CLIENT_SECRET=gJ3meMw0tG6ZuPqqxa6Qdocf8m6MdccM
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=keycloakdb;User=keycloakuser;Password=keycloakpass;
      ports:
         - "8008:8080"
      networks:
         - mynetwork
   appointment:
      build:
         context: .
         dockerfile: appointment/Dockerfile
      container_name: appointmentservice
      depends_on:
         rabbitmq:
            condition: service_healthy
      environment:
         - RABBITMQ_HOST=rabbitmq
      ports:
         - "8004:8000"
      networks:
         - mynetwork

   payment:
      build:
         context: ./payment/paymentDemo # <- pom.xml ve Dockerfile burada
         dockerfile: Dockerfile
      container_name: paymentservice
      depends_on:
         rabbitmq:
            condition: service_healthy
      environment:
         - RABBITMQ_HOST=rabbitmq

      ports:
         - "8006:8080"
      networks:
         - mynetwork
networks:
   mynetwork:
      driver: bridge
volumes:
   mysql_data:
