spring.application.name=paymentDemo
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.rabbitmq.host= rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username= guest
spring.rabbitmq.password= guest