spring:
   docker:
      compose:
         enabled: false
   rabbitmq:
      host: rabbitmq
      port: 5672
      username: guest
      password: guest
      

server:
   port: 8006
springdoc:
   api-docs:
      enabled: true
   swagger-ui:
      enabled: true
      path: /swagger-ui.html

iyzico:
  api-key: sandbox-bZDaE00vYDmsoPJtZxzFEebzKYwzuh6a
  secret-key: sandbox-JNF4z2HOtHHGJR2Q0JVjThxZ9Sa5xB0f
  base-url: https://sandbox-api.iyzipay.com
