<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d67cd013-939a-4f26-b7f5-52b6a313c081</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Keycloak.AuthServices.Authentication" Version="2.6.1" />
    <PackageReference Include="Keycloak.AuthServices.Authorization" Version="2.6.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <!-- <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" /> -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

</Project>
